### ISSUE TITLE
Missing resource

### ISSUE THREAD

**Issue by ghost** [ZaviiNet-Studios/MasterServer-Console#1]
Cannot compile, error is below, would like to do some contributing, but don't want to submit untested and broken code.

`Could not find file 'C:\Users\falle\repos\MasterServer-Console\MasterServer\servers.html'`

**Comment by ZaviiNet** [comment]
Thanks! I'll add it now

**Comment by ZaviiNet** [comment]
I have now added the missing file, Thanks for noticing it was missing! Any more questions open up an issue.

**Comment by ghost** [comment]
Works now, thanks!
