### ISSUE TITLE
When running using TFConsole Console Spams "Loading MasterServer-Console"

### ISSUE THREAD

**Issue by ZaviiNet** [ZaviiNet-Studios/MasterServer-Console#4]
When running using TFConsole Console Spams "Loading MasterServer-Console" 

If you convert back to Console.WriteLine  The Program works flawlessly, if you use TFConsole.WriteLine  the Console Spams "Loading MasterServer-Console" Then dies

@verlox You Added TFConsole, Does it work for you?

**Comment by ghost** [comment]
I actually just realized i forgot to dequeue the item, when i'm back from work i'll fix it, thanks for noticing!

**Comment by ghost** [comment]
Fixed, I created a new pull request
