### ISSUE TITLE
Access denied in method 

### ISSUE THREAD

**Issue by ghost** [ZaviiNet-Studios/MasterServer-Console#6]
Running the program currently returns this exception: `System.Net.HttpListenerException: 'Access is denied.'`, does not work in regular user or as an elevated user. Port is not taken by another application and is closed. Application is unable to open the port.

[Link to line](https://github.com/ZaviiNet-Studios/MasterServer-Console/blob/master/MasterServer/Program.cs#L324)

**Comment by ZaviiNet** [comment]
This issue has been fixed in Recent Commit, a Try catch method has been added to use Docker IP as Prefix but if Docker fails to use 127.0.0.1
